[package]
name = "rtempest"
version = "0.1.1"
edition = "2021"

[features]
default = []

[dependencies]
log = "0.4.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49", features = ["macros", "net", "rt-multi-thread", "sync"] }
